### ISSUE TITLE
بجای دکمه مشاهده باید دکمه کپی کردن لینک اضافه کنیم و گرافیک دکمه مشاهده کلا مناسب نیست خام زده شده. میشه کاستوم داخل مودالسوییت الرت گذاشت

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Editor#10]
بجای دکمه مشاهده باید دکمه کپی کردن لینک اضافه کنیم و گرافیک دکمه مشاهده کلا مناسب نیست خام زده شده. میشه کاستوم داخل مودالسوییت الرت گذاشت

**Comment by mohamadreza1388** [comment]
دکمه مشاهده رسما فقط برای اینه که ببینیم چجوری میشه توی سویت الرت یه دکمه گزاشت
وگرنه اصلا کاری نمیکنه
